### ISSUE TITLE
What is the dataset for open information extraction pretrainined model privided by allennlp

### ISSUE THREAD

**Issue by zhuango** [allenai/allennlp#3484]
I'm working on open information extraction task and I would like to know what is the dataset used to obtain the openie pretrained model at https://allennlp.s3.amazonaws.com/models/openie-model.2018-08-20.tar.gz.

I checked the config.json file contained in the above .tar file and find :
"train_data_path": "/inputs/training/nary_100k", 
"validation_data_path": "/inputs/validation/nary"
which are not accessible.

I also checked the website of openie demo at : https://demo.allennlp.org/open-information-extraction, saying that "The Open Information extractor was evaluated on the OIE2016 corpus." I download the corpus from https://github.com/gabrielStanovsky/oie-benchmark/blob/master/snapshot_oie_corpus.tar.gz and train openie model with hyper-parameters in the config.json contained in https://allennlp.s3.amazonaws.com/models/openie-model.2018-08-20.tar.gz. But the results are not matched with obtained from the allennlp pretrained model. Could you guys give some information about this? Thanks.

**Comment by brendan-ai2** [comment]
@gabrielStanovsky, could you chime in here? Thanks!

**Comment by bratao** [comment]
@zhuango did you find out? Can you share how you was able to train even using the OIE2016 corpus?

**Comment by zhuango** [comment]
Hi @bratao, I still wait for reply from @gabrielStanovsky about the data set.
I used preprocessed corpus (.conll) at [supervised-oie/supervised-oie-benchmark](https://github.com/gabrielStanovsky/supervised-oie/tree/master/supervised-oie-benchmark/oie_corpus), which is from this [corpus](https://github.com/gabrielStanovsky/oie-benchmark/blob/master/snapshot_oie_corpus.tar.gz) and this [script](https://github.com/gabrielStanovsky/supervised-oie/blob/master/supervised-oie-benchmark/create_oie_corpus.sh) I believe. 
The format of the above .conll files is not matched with the [format ](https://github.com/allenai/allennlp/tree/master/allennlp/tests/fixtures/data/open_information_extraction) that allennlp required for training openie model. But the .conll file can be converted to the required format following procedure like [this code](https://github.com/allenai/allennlp/blob/cd1d1b6bbd203e894aed5651a7938c0b09c2f773/allennlp/models/srl_util.py#L101). 
Hope it is helpful.

**Comment by bratao** [comment]
Thank you!!

**Comment by DeNeutoy** [comment]
Closing, issue is resolved!

**Comment by zhuango** [comment]
Hi @DeNeutoy, this issue is not resolved. I figured out how to train the openie model but still don't know the data sets used for the pretrained model provided by Allennlp project. I want to reproduce the precision of this pretrained model. So, I still need some help from @gabrielStanovsky. Is there something wrong with my training way or is dataset I use not the one that used for pretrained openie model？ Thank you guys very much.

**Comment by arleyprates** [comment]
Hello, I am also looking for this. I will be grateful

**Comment by gabrielStanovsky** [comment]
Hi, that sounds like the correct setup, what numbers are you getting? Do you compare it directly with the pretrained model at allennlp?

**Comment by MM-Vianai** [comment]
@gabrielStanovsky 
I am also facing similar problem. There have been some updates to the config file since the original post. based on answer provided for [this](https://github.com/allenai/allennlp/issues/5028) issue the correct config file to be used is : 

[https://raw.githubusercontent.com/allenai/allennlp-models/main/training_config/structured_prediction/srl.jsonnet](https://raw.githubusercontent.com/allenai/allennlp-models/main/training_config/structured_prediction/srl.jsonnet)

after following instructions on [oie-benchmark repo](https://github.com/gabrielStanovsky/oie-benchmark) I set environment variables in the config file as follows:
export SRL_TRAIN_DATA_PATH="oie-benchmark/oie_corpus/train.oie"
export SRL_VALIDATION_DATA_PATH="oie-benchmark/oie_corpus/test.oie"

and run the training command provided on allennlp demo:

`allennlp train https://raw.githubusercontent.com/allenai/allennlp-models/main/training_config/structured_prediction/srl.jsonnet -s output`

However, I get the following error:

`allennlp.common.checks.ConfigurationError: No embeddings of correct dimension found; you probably misspecified your embedding_dim parameter, or didn't pre-populate your Vocabulary`

are train.oie and test.oie correct data to be used?
