### ISSUE TITLE
Fix file friendly logging

### ISSUE THREAD

**Issue by brendan-ai2** [allenai/allennlp#3785]
@OyvindTafjord has identified a bug in our (formerly) file friendly logging that originated during the DistributedDataParallel additions. In short, `--file-friendly-logging` does not appear to work anymore.

To quote his Slack message:

> Regarding the lack of file-friendly logging: I'm guessing it's the distributed code (https://github.com/allenai/allennlp/pull/3529). As a workaround I hacked in the earlier code and that now works for my purposes (https://github.com/OyvindTafjord/allennlp/commit/8a1c7adaf78d3a1c2412312760b31192be936b0c). I also note that another change was that the stderr.log file for better or worse used to record these tqdm statuses, but with the new code that doesn't seem to happen (maybe that was intentional, but occasionally I have made use of those to get a post-hoc rough "training curve", although when using beaker those are also in the main beaker log).

**Comment by schmmd** [comment]
@DeNeutoy any idea on this one?

**Comment by dirkgr** [comment]
Should be fixed with #3519.

**Comment by schmmd** [comment]
@dirkgr thanks--I have not had time to look at this yet...

**Comment by matt-gardner** [comment]
@schmmd, we talked about this in our issue triage, and thought it should be covered by work I'm planning for #3519, so you shouldn't have to worry about this.

**Comment by schmmd** [comment]
How would we validate that this is indeed fixed now that #3519 is merged?

**Comment by DeNeutoy** [comment]
Now the issue that this is tracking with is #3913 , so it isn't fixed yet...

**Comment by schmmd** [comment]
This is independent of the other PRs and needs attention.

**Comment by matt-gardner** [comment]
Because there's some example code already that probably fixes the issue, I'm giving this one a "day" label.  Could be much less, if that example code just works without much effort, I just don't know.
